services:
  wallet-db:
    container_name: wallet_db
    build:
      context: ./services/wallet
      dockerfile: db.Dockerfile
    restart: on-failure
    env_file:
      - ./services/wallet/.env
    environment:
      POSTGRES_USER: ${WALLET_DB_USERNAME}
      POSTGRES_PASSWORD: ${WALLET_DB_PASSWORD}
      POSTGRES_DB: ${WALLET_DB_NAME}
    ports:
      - "4200:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  transaction-db:
    container_name: transaction_db
    build:
      context: ./services/transaction
      dockerfile: db.Dockerfile
    restart: on-failure
    env_file:
      - ./services/transaction/.env
    environment:
      POSTGRES_USER: ${TRANSACTION_DB_USERNAME}
      POSTGRES_PASSWORD: ${TRANSACTION_DB_PASSWORD}
      POSTGRES_DB: ${TRANSACTION_DB_NAME}
    ports:
      - "4202:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-db:
    container_name: user_db
    build:
      context: ./services/user
      dockerfile: db.Dockerfile
    restart: on-failure
    env_file:
      - ./services/user/.env
    environment:
      POSTGRES_USER: ${USER_DB_USERNAME}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
      POSTGRES_DB: ${USER_DB_NAME}
    ports:
      - "4205:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
    driver: local
