version: "3.8"
services:
  wallet-db:
    container_name: wallet_db
    build:
      context: ./services/wallet
      dockerfile: db.Dockerfile
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "4200:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  transaction-db:
    container_name: transaction_db
    build:
      context: ./services/transaction
      dockerfile: db.Dockerfile
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "4202:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
    driver: local
