name: CI

on:
  push:
    branches: ["master"]
    paths:
      - "services/**"
  pull_request:
    branches: ["master"]
    paths:
      - "services/**"

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      user_changed: ${{ steps.filter.outputs.user }}
      wallet_changed: ${{ steps.filter.outputs.wallet }}
      payment_changed: ${{ steps.filter.outputs.payment }}
      transaction_changed: ${{ steps.filter.outputs.transaction }}
      api_gateway_changed: ${{ steps.filter.outputs.api_gateway }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changes
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            user:
              - 'services/user/**'
            wallet:
              - 'services/wallet/**'
            payment:
              - 'services/payment/**'
            transaction:
              - 'services/transaction/**'
            api_gateway:
              - 'services/api-gateway/**'

  user-service:
    needs: detect-changes
    if: needs.detect-changes.outputs.user_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.2"

      - name: Build
        working-directory: services/user
        run: go build -v ./...

      - name: Test
        working-directory: services/user
        run: go test -v ./...

  wallet-service:
    needs: detect-changes
    if: needs.detect-changes.outputs.wallet_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.2"

      - name: Build
        working-directory: services/wallet
        run: go build -v ./...

      - name: Test
        working-directory: services/wallet
        run: go test -v ./...

  payment-service:
    needs: detect-changes
    if: needs.detect-changes.outputs.payment_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.2"

      - name: Build
        working-directory: services/payment
        run: go build -v ./...

      - name: Test
        working-directory: services/payment
        run: go test -v ./...

  transaction-service:
    needs: detect-changes
    if: needs.detect-changes.outputs.transaction_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.2"

      - name: Build
        working-directory: services/transaction
        run: go build -v ./...

      - name: Test
        working-directory: services/transaction
        run: go test -v ./...

  api-gateway-service:
    needs: detect-changes
    if: needs.detect-changes.outputs.api_gateway_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.2"

      - name: Build
        working-directory: services/api-gateway
        run: go build -v ./...

      - name: Test
        working-directory: services/api-gateway
        run: go test -v ./...
